### ISSUE TITLE
Self Host & Contribute

### ISSUE THREAD

**Issue by hng12** [tobias-inc/TobiasRework#41]
I want to contribute, but I need to be able to self host the bot first, so I can test out the commands, what is the start process? is it just `npm install` then `node index.js`?

**Comment by ghost** [comment]
In the first case, yes, but some gaps in the environment are necessary!

**Comment by hng12** [comment]
what other things do I need to install then?

**Comment by ghost** [comment]
Not necessarily install, but you will need a token bot to run your tests.
